/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beloningen` | `/beloningen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/persoonlijk` | `/persoonlijk`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/verzuim` | `/verzuim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/werktijden` | `/werktijden`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/department/[name]`, params: Router.UnknownInputParams & { name: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/beloningen` | `/beloningen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/persoonlijk` | `/persoonlijk`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/verzuim` | `/verzuim`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/werktijden` | `/werktijden`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/department/[name]`, params: Router.UnknownOutputParams & { name: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/beloningen${`?${string}` | `#${string}` | ''}` | `/beloningen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/persoonlijk${`?${string}` | `#${string}` | ''}` | `/persoonlijk${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/verzuim${`?${string}` | `#${string}` | ''}` | `/verzuim${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/werktijden${`?${string}` | `#${string}` | ''}` | `/werktijden${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/beloningen` | `/beloningen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/persoonlijk` | `/persoonlijk`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/verzuim` | `/verzuim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/werktijden` | `/werktijden`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/department/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/department/[name]`, params: Router.UnknownInputParams & { name: string | number; } };
    }
  }
}
